<?php
    if ($currentProduct = $block->getCurrentProduct())
    {
        /* 
        if($uahCourse = $block->getUahCourse())
        {
            echo "UAH: " . $currentProduct->getFinalPrice() * $uahCourse . "<br>";
        }
        if($rubCourse = $block->getRubCourse())
        {
            echo "RUB: " . $currentProduct->getFinalPrice() * $rubCourse . "<br>";
        }
        if($euroCourse = $block->getEuroCourse())
        {
            echo "Euro: " . $currentProduct->getFinalPrice() * $euroCourse . "<br>";
        }
 */     
        $availableCurrencyCodes = $block->getAvailableCurrencyCodes(true);

        foreach($availableCurrencyCodes as $code)
        {
            echo $code . ": " . $block->convertPriceFromCurrentToAnotherCurrency($currentProduct->getFinalPrice(), $code) . "<br>";
        }
    }
?>
