<div style="float: right; margin-left: 2%">
    <select id="city_select"></select>
</div>
<script>
require([
    'jquery'
], function($) {
    $.ajax({
        url: "http://api.ipstack.com/check?access_key=030df19a9a2eaa4742c6e537cc130c73&language=ru",
        type: "GET",
        success: function (res){
            var currCityInfo = res;
            $.ajax({
                url: "cities/cities/index",
                type: "POST",
                data: currCityInfo,
                success: function (res){
                    if(res){
                        $("#city_select").append($('<option>', {
                            value: res.entity_id,
                            text: res.city
                        }));
                        $('#city_select').val(res.entity_id);
                    }
                }
            })
            
        },
        error: function (xhr, status, error) {
            console.log(error);
        }
    })
    oblCenters = [
        {
            value: 17,
            text: "Вінниця"
        },
        {
            value: 1,
            text: "Дніпро"
        },
        {
            value: 109,
            text: "Донецьк"
        },
        {
            value: 21,
            text: "Житомир"
        },
        {
            value: 3,
            text: "Запоріжжя"
        },
        {
            value: 58,
            text: "Івано-Франківськ"
        },
        {
            value: 4,
            text: "Київ"
        },
        {
            value: 59,
            text: "Кропивницький"
        },
        {
            value: 110,
            text: "Луганськ"
        },
        {
            value: 22,
            text: "Луцьк"
        },
        {
            value: 8,
            text: "Львів"
        },
        {
            value: 9,
            text: "Миколаїв"
        },
        {
            value: 10,
            text: "Одеса"
        },
        {
            value: 11,
            text: "Полтава"
        },
        {
            value: 18,
            text: "Рівне"
        },
        {
            value: 56,
            text: "Суми"
        },
        {
            value: 19,
            text: "Тернопіль"
        },
        {
            value: 63,
            text: "Ужгород"
        },
        {
            value: 13,
            text: "Харків"
        },
        {
            value: 14,
            text: "Херсон"
        },
        {
            value: 15,
            text: "Хмельницький"
        },
        {
            value: 62,
            text: "Черкаси"
        },
        {
            value: 20,
            text: "Чернівці"
        },
        {
            value: 57,
            text: "Чернігів"
        }
    ];
    oblCenters.forEach((el) => {
        $("#city_select").append($('<option>', el));
    });
})
</script>