<?php

    $viewModel = $block->getData('view_model');
    $product = $block->getProduct();

    $timeUntilEnd = $viewModel->getTimeUntilEnd($product);

    if(!is_null($timeUntilEnd))
    {
        echo '<b>Special price offer end in: </b>';
        echo (int)($timeUntilEnd / 86400) . ' days ';
        $timeUntilEnd %= 86400;
        echo (int)($timeUntilEnd / 3600) . ' hours ';
        $timeUntilEnd %= 3600;
        echo (int)($timeUntilEnd / 60) . ' minutes ';
        $timeUntilEnd %= 60;
        echo (int)($timeUntilEnd) . ' seconds ';
    }
?>