<?php
    $viewModel = $block->getData("view_model");

    $currentProduct = $viewModel->getCurrentProduct();
    if($viewModel->isProductSocial($currentProduct) && $viewModel->isSocialEnabled())
    {
        $discount = $viewModel->getDiscount();
        $price = $currentProduct->getPrice();
        $name = $currentProduct->getName();
        echo "<h2>$name SOCIAL!!!</h2>";
        echo "Скидка на социальный продукт <b>" . $discount * 100 . "%</b><br>";
        echo "Стоимость с учетом скидки <b>" . $price - $price * $discount . "$</b><br>";
    }
?>