<?php
/** @var \Magento\Sales\Block\Order\History $block */
    $viewModel = $block->getData('view_model');
    $isModuleEnabled = $viewModel->isModuleEnabled();
?>
<div id="modal-content">
    <form method="POST" id="order-cancelation-form"
    action="<?= $block->getBaseUrl() . 'cancelorder/index/cancel'?>">
        <fieldset class="fieldset">
            <input type="hidden" name="order-id" id="order-id" title="Order Id" class="input-text required-entry" type="text"/>
            <div class="field required">
                <label class="label" for="canc-reason">Select cancellation reason</label>
                <div class="control">
                    <select form="order-cancelation-form" class="required-entry" name="canc-reason" id="canc-reason">
                        <option value="alt">I found a cheaper alternative</option>
                        <option value="dupl">I placed a duplicate order</option>
                        <option value="del">Delivery takes to long</option>
                        <option value="wrng">I bought the wrong item(s)</option>
                        <option value="nfb">I recieved negative feedback about the item after purchase</option>
                        <option value="lse">Else</option>
                    </select>
                </div>
            </div>
            <div class="field comment">
                <label class="label" for="canc-comment">Leave a Comment</label>
                <div class="control">
                    <textarea name="canc-comment" id="canc-comment" title="Question" class="input-text" type="text" cols="5" rows="3"></textarea>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
           <div class="primary">
               <button type="submit" title="<?php  echo __('Submit') ?>" class="action submit primary" id="custom_btn">
                   <span><?php  echo __('Submit') ?></span>
               </button>
           </div>
        </div>
    </form>
</div>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order) : ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra) : ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                            <?php if ($isModuleEnabled && $_order->getStatusLabel() == 'Pending') : ?>
                                <button value="<?= $block->escapeHtml($_order->getRealOrderId()) ?>" class="cancel-order">Cancel</button>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: 'Cancel Order',
            buttons: [{
                text: $.mage.__('Close'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        }

        modal(options, $('#modal-content'));
        $('.cancel-order').each((index, element) => {
            $(element).on('click', () => {
                $('#modal-content').modal("openModal");
                $('#order-id').val($(element).val());
            })
        })
    });
</script>